- name: Apt installs 
  apt:
    state: latest
    name:
      - rxvt-unicode
      - xfonts-terminus
    update_cache: true

- name: cp .XResources
  copy: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: '.Xresources' , dest: '~/.Xresources' }
    - { src: '.bashrc' , dest: '~/.bashrc' }
    - { src: '90s.xrs' , dest: '~/90s.xrs' }
    - { src: 'Red.xrs' , dest: '~/Red.xrs' }
    - { src: 'Daylight.xrs' , dest: '~/Daylight.xrs' }
  become_user: "{{ user }}"

- name: cp .bashrc
  copy:
    src: .bashrc
    dest: ~/.bashrc
  become_user: "{{ user }}"

