- name: Apt installs 
  apt:
    state: latest
    name:
      - rxvt-unicode
    update_cache: yes

- name: cp .XResources
  copy:
    src: .Xresources
    dest: ~/.Xresources

- name: cp .bashrc
  copy:
    src: .bashrc
    dest: ~/.bashrc

