- name: Add Codium keyring && repo
  shell:
    cmd: wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg && echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | tee /etc/apt/sources.list.d/vscodium.list
  creates: /etc/apt/sources.list.d/vscodium.list

- name: Apt installs 
  apt:
    state: latest
    name:
      - codium

- name: Move keybind pref
  file: 
    path: ~/.config/VSCodium/
    state: directory
  become_user: "{{ user }}"

- name: Codium user prefs copy
  copy: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: 'keybindings.json' , dest: '~/.config/VSCodium/' }
    - { src: 'extensions.txt' , dest: '~/.config/VSCodium/' }
  become_user: "{{ user }}"

- name: Install Codium extensions
  shell:
    cmd: cat extensions.txt | xargs -n 1 codium --install-extension
  become_user: "{{ user }}"
