- name: Grab Firefox dev tarball
  shell: 
    cmd: wget "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" -O /tmp/Firefox-dev.tar.bz2

- name: Untar in /opt
  shell:
    cmd: tar xjf /tmp/Firefox-dev.tar.bz2 -C /opt/

- name: Softlink to ffd
  shell:
    cmd: ln -s /opt/firefox/firefox /usr/local/bin/ffd